interface Props {
  id: string;
  /** Template name — used to build the alt text. */
  name: string;
  height?: number;
  /**
   * Set on the handful of thumbnails above the fold. Everything else stays
   * lazy: a grid of sixteen must not open sixteen connections at once.
   */
  priority?: boolean;
}

/**
 * Static thumbnail for a template, for use in grids.
 *
 * This replaced a live <iframe> per card. Sixteen cards meant sixteen nested
 * browsing contexts, each laying out a document at 1440px and scaling it down,
 * plus a ResizeObserver per card to measure that scale. The teaser HTML is only
 * ~1.4 kB, so bandwidth was never the problem — the cost was creating and
 * laying out sixteen documents on the main thread. On a phone the grid is one
 * column, so lazy loading deferred nearly all of them and the page felt fine;
 * on desktop three columns put 6-9 iframes in the first viewport and they all
 * started together. Hence fast on mobile, slow on desktop.
 *
 * A plain <img> has none of that: no document, no observer, no JavaScript, and
 * the browser decodes it off the main thread. Images come from public/thumbs/,
 * generated by `npm run thumbs`.
 *
 * Deliberately not next/image: these are fixed-size, already-optimised WebP at
 * exactly the density the card needs, so the resizing proxy would add a
 * server-side transform and a cache lookup to save nothing.
 */
export function TemplateThumb({ id, name, height = 220, priority = false }: Props) {
  return (
    <div
      style={{
        height,
        width: "100%",
        overflow: "hidden",
        position: "relative",
        // Shows through until the image decodes. Without it a slow decode left
        // a white block that flashed against the dark card.
        background: "#0f0f0f",
        flexShrink: 0,
        borderRadius: "inherit",
      }}
    >
      <img
        src={`/thumbs/${id}.webp`}
        alt={`Anteprima — ${name}`}
        // Intrinsic size is stated so the browser reserves the box before the
        // image arrives; the grid must not reflow as sixteen of these land.
        width={720}
        height={450}
        loading={priority ? "eager" : "lazy"}
        decoding="async"
        fetchPriority={priority ? "high" : "low"}
        style={{
          display: "block",
          width: "100%",
          height: "100%",
          objectFit: "cover",
          objectPosition: "top",
        }}
      />

      {/* Fades the image into the card below it. */}
      <div
        aria-hidden
        style={{
          position: "absolute",
          inset: 0,
          background: "linear-gradient(to bottom, transparent 55%, var(--surface) 100%)",
          pointerEvents: "none",
        }}
      />
    </div>
  );
}
